import Thought from "../models/Thought.js";
import { Request, Response } from "express";

//Using find() to get all thoughts.
export const getAllThoughts = async (_req: Request, res: Response) => {
  try {
    const thoughts = await Thought.find();
    res.json(thoughts);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
};

//Using findById() and passing the thoughtId, generated by MongoDB, in order to get a specific user.
export const getThoughtById = async (req: Request, res: Response) => {
  try {
    const thought = await Thought.findById(req.params.thoughtId);
    if (!thought) {
      res.status(404).json({ error: "Thought not found." });
    } else {
      res.status(200).json(thought);
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
};
//Using findByIdAndUpdate to update a specific thought using its ID.
export const updateThought = async (req: Request, res: Response) => {
  try {
    const updateThought = await Thought.findByIdAndUpdate(
      req.params.thoughtId,
      req.body,
      { new: true, runValidators: true } //checking that the updated information is valid.
    );
    if (!updateThought) {
      res.status(404).json("Error: Thought not found.");
    } else {
      res.status(200).json(updateThought);
    }
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
};
//Using create() to create a new thought.
export const createThought = async (req: Request, res: Response) => {
  try {
    const createThought = await Thought.create(req.body);
    res.json(createThought);
  } catch (err: any) {
    res.status(400).json({ error: err.message });
  }
};
//Using findByIdAndDelete() and passing the thoughtId to delete a specific user.
export const deleteThought = async (req: Request, res: Response) => {
  try {
    const deleteThought = await Thought.findByIdAndDelete(req.params.thoughtId);
    if (!deleteThought) {
      res.status(404).json("Error: Thought not found.");
    } else {
      res.status(200).json("Thought successfully deleted.");
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
};
//Using findByIdAndUpdate to push a new reaction to the reactions array for this thought.
export const createReaction = async (
  req: Request,
  res: Response
): Promise<void> => {
  try {
    const { thoughtId } = req.params;
    const { reactionBody, username } = req.body;

    const updatedThought = await Thought.findByIdAndUpdate(
      thoughtId,
      {
        $push: { reactions: { reactionBody, username } },
      },
      { new: true }
    );

    if (!updatedThought) {
      res.status(404).json({ message: "Thought not found" });
    } else {
      res.status(200).json(updatedThought);
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
    return;
  }
};
//Using findByIdAndUpdate to pull (remove) a reaction from the reactions array for this thought.
export const deleteReaction = async (
  req: Request,
  res: Response
): Promise<void> => {
  try {
    const { thoughtId, reactionId } = req.params;

    const updatedThought = await Thought.findByIdAndUpdate(
      thoughtId,
      {
        $pull: { reactions: { reactionId } },
      },
      { new: true }
    );

    if (!updatedThought) {
      res.status(404).json({ message: "Thought not found" });
    } else {
      res.status(200).json(updatedThought);
    }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
    return;
  }
};
